name: Deploy to Preview Channel

on:
  pull_request:
    paths:
    - "content/**"

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.119.0'
          # extended: true
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache-dependency-path: content/ai_exchange/go.sum

      - name: Cache Hugo modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/hugo_cache
            content/ai_exchange/resources
          key: ${{ runner.os }}-hugo-${{ hashFiles('content/ai_exchange/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-hugo-

      - name: Build
        run: |
         cd content/ai_exchange
         hugo mod get
         hugo --gc --minify
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          expires: 3d
          projectId: project-integration-standards
          target: owasp-ai-exchange
          entryPoint: content/ai_exchange
